# Generated by Django 4.2.7 on 2025-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_mgmt", "0003_knowledgebase_result_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="rerank_top_k",
            field=models.IntegerField(default=10, verbose_name="Rerank Top K"),
        ),
    ]
