default_stages: [commit]
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: ["flake8>=4.0.1"]
      language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
  - repo: local
    hooks:
      - id: check-migrate
        name: check migrate
        entry: python scripts/check_migrate/check_migrate.py
        language: system
        types: [python]
      - id: check-commit-message
        name: Check commit message
        entry: python scripts/check_commit_message.py
        language: system
        stages: [commit-msg]
      - id: check-requirements
        name: Check Requirements
        entry: python scripts/check_requirements.py
        language: system
