# Generated by Django 4.2.7 on 2024-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPISecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("api_secret", models.CharField(max_length=64)),
                (
                    "team",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Time Fields",
                "abstract": False,
            },
        ),
    ]
