# Generated by Django 4.2.7 on 2024-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_userapisecret_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "target_type",
                    models.CharField(max_length=10, verbose_name="Target Type"),
                ),
                (
                    "target_list",
                    models.JSONField(default=list, verbose_name="Target List"),
                ),
                (
                    "rule_type",
                    models.CharField(max_length=10, verbose_name="Rule Type"),
                ),
                ("file_size", models.FloatField(default=0, verbose_name="Total Size")),
                ("unit", models.CharField(max_length=10, verbose_name="Size Unit")),
                (
                    "skill_count",
                    models.IntegerField(default=0, verbose_name="Skill Count"),
                ),
                ("bot_count", models.IntegerField(default=0, verbose_name="Bot Count")),
            ],
            options={
                "verbose_name": "Time Fields",
                "abstract": False,
            },
        ),
    ]
