# Generated by Django 4.2.7 on 2025-03-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_userapisecret_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTokenUseInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("group", models.CharField(max_length=100, unique=True, verbose_name="Group")),
                ("llm_model", models.CharField(max_length=100, verbose_name="LLM Model")),
                ("used_token", models.BigIntegerField(verbose_name="Used Token")),
            ],
            options={
                "verbose_name": "Time Fields",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="quotarule",
            name="token_set",
            field=models.JSONField(default=list, verbose_name="Token Set"),
        ),
    ]
