# Generated by Django 4.2.7 on 2025-03-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_teamtokenuseinfo_quotarule_token_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamtokenuseinfo",
            options={},
        ),
        migrations.AlterField(
            model_name="teamtokenuseinfo",
            name="group",
            field=models.CharField(max_length=100, verbose_name="Group"),
        ),
        migrations.AlterUniqueTogether(
            name="teamtokenuseinfo",
            unique_together={("group", "llm_model")},
        ),
    ]
