# Generated by Django 4.2.7 on 2024-11-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("name", models.CharField(max_length=255, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("condition", models.JSONField(default=dict, verbose_name="条件")),
                (
                    "action",
                    models.IntegerField(choices=[(0, "Use specified knowledge base")], default=0, verbose_name="动作"),
                ),
                ("action_set", models.JSONField(default=dict, verbose_name="动作设置")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_provider_mgmt.llmskill",
                        verbose_name="技能",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintainer Fields",
                "abstract": False,
            },
        ),
    ]
