# Generated by Django 4.2.7 on 2024-11-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0003_tokenconsumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenconsumption",
            name="bot_id",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
