# Generated by Django 4.2.7 on 2025-01-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0004_tokenconsumption_bot_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("current_ip", models.GenericIPAddressField()),
                ("state", models.BooleanField(default=True)),
                ("request_detail", models.JSONField(default=dict)),
                ("response_detail", models.JSONField(default=dict)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_provider_mgmt.llmskill",
                        verbose_name="技能",
                    ),
                ),
            ],
        ),
    ]
