# Generated by Django 4.2.7 on 2025-02-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0005_skillrequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillrequestlog",
            name="user_message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="llm_model_type",
            field=models.CharField(
                choices=[("chat-gpt", "ChatGPT"), ("zhipu", "智谱AI"), ("deep-seek", "DeepSeek")],
                max_length=255,
                verbose_name="LLM模型类型",
            ),
        ),
    ]
