# Generated by Django 4.2.7 on 2025-02-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0007_llmmodel_is_build_in_llmmodel_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="show_think",
            field=models.BooleanField(default=True),
        ),
    ]
