# Generated by Django 4.2.7 on 2025-02-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0009_embedprovider_team_ocrprovider_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="tools",
            field=models.JSONField(default=list),
        ),
    ]
