# Generated by Django 4.2.7 on 2025-03-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0011_skilltools"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltools",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="skilltools",
            name="icon",
            field=models.CharField(default="", max_length=100),
        ),
    ]
