# Generated by Django 4.2.7 on 2025-03-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0012_skilltools_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="consumer_team",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]
