# Generated by Django 4.2.7 on 2025-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0013_llmmodel_consumer_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
    ]
