# Generated by Django 4.2.7 on 2025-03-19 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0014_alter_llmmodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skilltools",
            name="display_name",
        ),
    ]
