# Generated by Django 4.2.7 on 2025-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0015_remove_skilltools_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltools",
            name="is_build_in",
            field=models.BooleanField(default=False),
        ),
    ]
