# Generated by Django 4.2.7 on 2025-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0016_skilltools_is_build_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
