# Generated by Django 4.2.7 on 2024-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0002_remove_bot_channels_botchannel_bot_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="api_token",
            field=models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="API Token"),
        ),
    ]
