# Generated by Django 4.2.7 on 2024-10-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0003_bot_api_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=100, verbose_name="用户ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True, verbose_name="名称")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("enterprise_wechat", "Enterprise WeChat"),
                            ("enterprise_wechat_bot", "Enterprise WeChat Bot"),
                            ("ding_talk", "Ding Talk"),
                            ("web", "Web"),
                            ("gitlab", "GitLab"),
                        ],
                        max_length=100,
                        verbose_name="channel type",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息通道用户",
                "verbose_name_plural": "消息通道用户",
            },
        ),
        migrations.RemoveField(
            model_name="botconversationhistory",
            name="user_info",
        ),
        migrations.AddField(
            model_name="botconversationhistory",
            name="channel_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot_mgmt.channeluser",
                verbose_name="通道用户",
            ),
        ),
    ]
