# Generated by Django 4.2.7 on 2024-11-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0004_channeluser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField(verbose_name="问题")),
                ("content", models.TextField(verbose_name="内容")),
                ("knowledge_base_id", models.IntegerField(verbose_name="知识库ID")),
                ("knowledge_document_id", models.IntegerField(verbose_name="知识文档ID")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_mgmt.botconversationhistory",
                        verbose_name="回答",
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
