# Generated by Django 4.2.7 on 2025-01-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0007_alter_botchannel_channel_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("group_id", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("enterprise_wechat", "Enterprise WeChat"),
                            ("enterprise_wechat_bot", "Enterprise WeChat Bot"),
                            ("wechat_official_account", "WeChat Official Account"),
                            ("ding_talk", "Ding Talk"),
                            ("web", "Web"),
                            ("gitlab", "GitLab"),
                        ],
                        max_length=100,
                        verbose_name="channel type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_mgmt.channelgroup")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_mgmt.channeluser")),
            ],
        ),
    ]
