# Generated by Django 4.2.7 on 2025-02-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0008_channelgroup_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="replica_count",
            field=models.IntegerField(default=1, verbose_name="端口映射"),
        ),
    ]
