# Generated by Django 4.2.7 on 2025-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_mgmt", "0009_bot_replica_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="replica_count",
            field=models.IntegerField(default=1, verbose_name="副本数量"),
        ),
    ]
