MENUS = [
    {
        "client_id": "munchkin",
        "name": "OpsPilot",
        "url": "/opspilot/studio",
        "description": "Create roles for the OpsPilot app to manage data permissions, menu permissions, and feature permissions.",  # noqa
        "menus": [
            {
                "name": "Studio",
                "children": [
                    {
                        "id": "bot_list",
                        "name": "Bot-list",
                        "title": "Studio",
                        "url": "/opspilot/studio",
                        "operation": ["View", "Add", "Edit", "Delete"],
                    },
                    {
                        "id": "bot_settings",
                        "name": "Bot-Setting",
                        "title": "Settings",
                        "url": "/opspilot/studio/detail/settings",
                        "operation": ["View", "Edit", "Save&Publish"],
                    },
                    {
                        "id": "bot_channel",
                        "name": "Bot-Channel",
                        "title": "Channel",
                        "url": "/opspilot/studio/detail/channel",
                        "operation": ["View", "Setting"],
                    },
                    {
                        "id": "bot_conversation_log",
                        "name": "Bot-Conversation-Log",
                        "title": "Conversation Logs",
                        "url": "/opspilot/studio/detail/logs",
                        "operation": ["View", "Mark"],
                    },
                    {
                        "id": "bot_statistics",
                        "name": "Bot-Statistics",
                        "title": "Statistics",
                        "url": "/opspilot/studio/detail/statistics",
                        "operation": ["View"],
                    },
                ],
            },
            {
                "name": "Skill",
                "children": [
                    {
                        "id": "skill_list",
                        "name": "Skill-list",
                        "title": "Skill",
                        "url": "/opspilot/skill",
                        "operation": ["View", "Add", "Edit", "Delete"],
                    },
                    {
                        "id": "skill_setting",
                        "name": "Skill-Setting",
                        "title": "Setting",
                        "url": "/opspilot/skill/detail/settings",
                        "operation": ["View", "Edit"],
                    },
                    {
                        "id": "skill_rule",
                        "name": "Skill-Rule",
                        "title": "Rules",
                        "url": "/opspilot/skill/detail/rules",
                        "operation": ["View", "Add", "Edit", "Delete"],
                    },
                    {
                        "id": "skill_api",
                        "name": "Skill-Api",
                        "title": "API",
                        "url": "/opspilot/skill/detail/api",
                        "operation": ["View"],
                    },
                ],
            },
            {
                "name": "Knowledge",
                "children": [
                    {
                        "id": "knowledge_list",
                        "name": " Knowledge-list",
                        "title": "Knowledge",
                        "url": "/opspilot/knowledge",
                        "operation": ["View", "Add", "Edit", "Delete"],
                    },
                    {
                        "id": "knowledge_document",
                        "name": " Knowledge-Document",
                        "title": "Documents",
                        "url": "/opspilot/knowledge/detail/documents",
                        "operation": ["View", "Add", "Set", "Train", "Delete"],
                    },
                    {
                        "id": "knowledge_testing",
                        "name": " Knowledge-Testing",
                        "title": "Testing",
                        "url": "/opspilot/knowledge/detail/testing",
                        "operation": ["View", "Edit"],
                    },
                    {
                        "id": "knowledge_setting",
                        "name": " Knowledge-Setting",
                        "title": "Settings",
                        "url": "/opspilot/knowledge/detail/settings",
                        "operation": ["View", "Edit"],
                    },
                    {
                        "id": "knowledge_api",
                        "name": " Knowledge-API",
                        "title": "API",
                        "url": "/opspilot/knowledge/detail/api",
                        "operation": ["View"],
                    },
                ],
            },
            {
                "name": "Provide",
                "children": [
                    {
                        "id": "provide_list",
                        "name": "Provide-list",
                        "title": "Provider",
                        "url": "/opspilot/provider",
                        "operation": ["View", "Setting"],
                    },
                ],
            },
            {
                "name": "Setting",
                "children": [
                    {
                        "id": "api_secret_key",
                        "name": "API Secret Key",
                        "title": "API Secret Keys",
                        "url": "/opspilot/settings/key",
                        "operation": ["View", "Add", "Delete"],
                    },
                    {
                        "id": "mange_quota",
                        "name": "Mange Quota",
                        "title": "Manage Quota",
                        "url": "/opspilot/settings",
                        "operation": ["View", "Add", "Edit", "Delete"],
                    },
                    {
                        "id": "my_quota",
                        "name": "My Quota",
                        "title": "My Quota",
                        "url": "/opspilot/settings/quota",
                        "operation": ["View"],
                    },
                ],
            },
        ],
        "roles": [
            {"name": "admin", "role_name": "munchkin_admin", "menus": []},
            {
                "name": "normal",
                "role_name": "munchkin_normal",
                "menus": [
                    "api_secret_key-View",
                    "bot_channel-View",
                    "bot_conversation_log-View",
                    "bot_list-View",
                    "bot_settings-View",
                    "bot_statistics-View",
                    "knowledge_api-View",
                    "knowledge_document-View",
                    "knowledge_list-View",
                    "knowledge_setting-View",
                    "knowledge_testing-View",
                    "mange_quota-View",
                    "my_quota-View",
                    "provide_list-View",
                    "skill_api-View",
                    "skill_list-View",
                    "skill_rule-View",
                    "skill_setting-View",
                ],
            },
        ],
    },
]
