# Generated by Django 4.2.7 on 2025-01-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorinstance',
            name='agent_id',
        ),
    ]
