# Generated by Django 4.2.7 on 2025-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_monitorinstance_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='no_data_alert',
        ),
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='source',
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='no_data_period',
            field=models.JSONField(default=dict, verbose_name='无数据告警的数据周期（eg:10m内无数据）'),
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='query_condition',
            field=models.JSONField(default=dict, verbose_name='查询条件'),
        ),
        migrations.AlterField(
            model_name='monitorpolicy',
            name='organizations',
            field=models.JSONField(default=list, verbose_name='策略所属组织'),
        ),
    ]
