# Generated by Django 4.2.7 on 2025-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_monitorpolicy_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='no_data_recovery_period',
            field=models.JSONField(default=dict, verbose_name='无数据告警恢复的数据周期（eg:10m内有数据）'),
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='source',
            field=models.JSONField(default=dict, verbose_name='策略适用的资源'),
        ),
    ]
