# Generated by Django 4.2.7 on 2025-01-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitorpolicy_no_data_recovery_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='collect_type',
            field=models.CharField(default='', max_length=50, verbose_name='采集类型'),
        ),
    ]
