# Generated by Django 4.2.7 on 2025-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitorpolicy_alert_name_monitoreventrawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='monitor_instance_name',
            field=models.CharField(default='', max_length=100, verbose_name='监控对象实例名称'),
        ),
    ]
