# Generated by Django 4.2.7 on 2025-02-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_monitoralert_monitor_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='info_event_count',
            field=models.IntegerField(default=0, verbose_name='信息事件数量'),
        ),
    ]
