# Generated by Django 4.2.7 on 2025-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_monitoralert_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='instance_id_keys',
            field=models.JSONField(default=list, verbose_name='实例ID键(由指标维度组成)'),
        ),
    ]
