# Generated by Django 4.2.7 on 2025-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_metric_instance_id_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorpolicy',
            name='algorithm',
            field=models.CharField(max_length=50, verbose_name='聚合算法'),
        ),
    ]
