# Generated by Django 4.2.7 on 2025-03-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='notice_type_id',
            field=models.CharField(default='', max_length=100, verbose_name='通知方式ID'),
        ),
        migrations.AlterField(
            model_name='monitorpolicy',
            name='notice_type',
            field=models.CharField(default='', max_length=50, verbose_name='通知方式'),
        ),
    ]
