# Generated by Django 4.2.7 on 2025-03-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_monitorpolicy_notice_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='notice_type_id',
        ),
    ]
