# Generated by Django 4.2.7 on 2025-03-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_remove_monitorpolicy_notice_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='notice_type_id',
            field=models.IntegerField(default=0, verbose_name='通知方式ID'),
        ),
    ]
