# Generated by Django 4.2.7 on 2025-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_monitorpolicy_notice_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorinstance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
