# Generated by Django 4.2.7 on 2024-10-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collector",
            fields=[
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="采集器ID")),
                ("name", models.CharField(max_length=100, verbose_name="采集器名称")),
                (
                    "service_type",
                    models.CharField(choices=[("exec", "执行任务"), ("svc", "服务")], max_length=100, verbose_name="服务类型"),
                ),
                (
                    "node_operating_system",
                    models.CharField(
                        choices=[("linux", "Linux"), ("windows", "Windows")], max_length=50, verbose_name="节点操作系统类型"
                    ),
                ),
                ("executable_path", models.CharField(max_length=200, verbose_name="可执行文件路径")),
                ("execute_parameters", models.CharField(max_length=200, verbose_name="执行参数")),
                ("validation_parameters", models.CharField(max_length=200, verbose_name="验证参数")),
                ("default_template", models.TextField(verbose_name="默认模板")),
            ],
            options={
                "verbose_name": "采集器信息",
                "db_table": "collector",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="节点ID")),
                ("name", models.CharField(max_length=100, verbose_name="节点名称")),
                ("ip", models.CharField(max_length=30, verbose_name="IP地址")),
                (
                    "operating_system",
                    models.CharField(
                        choices=[("linux", "Linux"), ("windows", "Windows")], max_length=50, verbose_name="操作系统类型"
                    ),
                ),
                ("collector_configuration_directory", models.CharField(max_length=200, verbose_name="采集器配置目录")),
                ("metrics", models.JSONField(default=dict, verbose_name="指标")),
                ("status", models.JSONField(default=dict, verbose_name="状态")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("log_file_list", models.JSONField(default=list, verbose_name="日志文件列表")),
            ],
            options={
                "verbose_name": "节点信息",
                "db_table": "node",
            },
        ),
        migrations.CreateModel(
            name="SidecarApiToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("token", models.CharField(max_length=100, verbose_name="Token")),
            ],
            options={
                "verbose_name": "Sidecar API Token",
                "db_table": "sidecar_api_token",
            },
        ),
        migrations.CreateModel(
            name="SidecarEnv",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Sidecar环境变量",
                "db_table": "sidecar_env",
            },
        ),
        migrations.CreateModel(
            name="CollectorConfiguration",
            fields=[
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="配置ID")),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("config_template", models.TextField(verbose_name="配置模板")),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="node_mgmt.collector", verbose_name="采集器"
                    ),
                ),
                ("nodes", models.ManyToManyField(to="node_mgmt.node", verbose_name="节点")),
            ],
            options={
                "verbose_name": "采集器配信息",
                "db_table": "collector_configuration",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("action", models.JSONField(default=list, verbose_name="操作")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="node_mgmt.node", verbose_name="节点"
                    ),
                ),
            ],
            options={
                "verbose_name": "操作信息",
                "db_table": "action",
            },
        ),
    ]
