# Generated by Django 4.2.7 on 2025-01-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfiguration',
            name='is_pre',
            field=models.BooleanField(default=False, verbose_name='是否预定义'),
        ),
        migrations.CreateModel(
            name='ChildConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('collect_type', models.CharField(max_length=50, verbose_name='采集对象类型')),
                ('config_type', models.CharField(max_length=50, verbose_name='配置类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('collector_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.collectorconfiguration', verbose_name='采集器配置')),
            ],
            options={
                'verbose_name': '子配置',
                'verbose_name_plural': '子配置',
                'db_table': 'child_config',
            },
        ),
    ]
