# Generated by Django 4.2.7 on 2024-10-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '操作信息', 'verbose_name_plural': '操作信息'},
        ),
        migrations.AlterModelOptions(
            name='collector',
            options={'verbose_name': '采集器信息', 'verbose_name_plural': '采集器信息'},
        ),
        migrations.AlterModelOptions(
            name='collectorconfiguration',
            options={'verbose_name': '采集器配信息', 'verbose_name_plural': '采集器配信息'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '节点信息', 'verbose_name_plural': '节点信息'},
        ),
        migrations.AlterModelOptions(
            name='sidecarapitoken',
            options={'verbose_name': 'Sidecar API Token', 'verbose_name_plural': 'Sidecar API Token'},
        ),
        migrations.AlterModelOptions(
            name='sidecarenv',
            options={'verbose_name': 'Sidecar环境变量', 'verbose_name_plural': 'Sidecar环境变量'},
        ),
        migrations.AlterField(
            model_name='collector',
            name='default_template',
            field=models.TextField(blank=True, null=True, verbose_name='默认模板'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='validation_parameters',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='验证参数'),
        ),
        migrations.AlterField(
            model_name='collectorconfiguration',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='node_mgmt.node', verbose_name='节点'),
        ),
    ]
