# Generated by Django 4.2.7 on 2024-12-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0002_alter_action_options_alter_collector_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='云区域名称')),
                ('introduction', models.TextField(blank=True, verbose_name='云区域介绍')),
            ],
            options={
                'verbose_name': '云区域',
                'verbose_name_plural': '云区域',
                'db_table': 'cloud_region',
            },
        ),
        migrations.AlterModelOptions(
            name='collectorconfiguration',
            options={'verbose_name': '采集器配置信息', 'verbose_name_plural': '采集器配置信息'},
        ),
        migrations.AddField(
            model_name='collector',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='采集器介绍'),
        ),
        migrations.AddField(
            model_name='sidecarenv',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='collectorconfiguration',
            name='config_template',
            field=models.TextField(blank=True, verbose_name='配置模板'),
        ),
        migrations.AlterField(
            model_name='sidecarenv',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='collectorconfiguration',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidecarenv',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sidecarenv',
            unique_together={('key', 'cloud_region')},
        ),
    ]
