# Generated by Django 4.2.7 on 2025-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0002_collectorconfiguration_is_pre_childconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='childconfig',
            name='collect_instance_id',
            field=models.CharField(default='', max_length=100, verbose_name='采集对象实例ID'),
        ),
    ]
