# Generated by Django 4.2.7 on 2025-01-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0003_childconfig_collect_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorconfiguration',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='配置名称'),
        ),
    ]
