# Generated by Django 4.2.7 on 2025-01-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0003_cloudregion_alter_collectorconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorconfiguration',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
        ),
        migrations.AlterField(
            model_name='node',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
        ),
        migrations.AlterField(
            model_name='sidecarenv',
            name='cloud_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域'),
        ),
        migrations.CreateModel(
            name='NodeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('organization', models.CharField(max_length=100, verbose_name='组织id')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点组织',
                'verbose_name_plural': '节点组织',
                'db_table': 'node_organization',
                'unique_together': {('node', 'organization')},
            },
        ),
    ]
