# Generated by Django 4.2.7 on 2025-02-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0004_alter_collectorconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childconfig',
            name='collect_instance_id',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='采集对象实例ID'),
        ),
    ]
