# Generated by Django 4.2.7 on 2025-03-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0005_alter_childconfig_collect_instance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('type', models.CharField(max_length=100, verbose_name='任务类型')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '采集器任务',
                'verbose_name_plural': '采集器任务',
                'db_table': 'collector_task',
            },
        ),
        migrations.CreateModel(
            name='ControllerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('type', models.CharField(max_length=100, verbose_name='任务类型')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
                ('work_node', models.CharField(blank=True, max_length=100, verbose_name='工作节点')),
                ('cloud_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域')),
            ],
            options={
                'verbose_name': '控制器任务',
                'verbose_name_plural': '控制器任务',
                'db_table': 'controller_task',
            },
        ),
        migrations.CreateModel(
            name='ControllerTaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP地址')),
                ('os', models.CharField(max_length=100, verbose_name='操作系统')),
                ('organizations', models.JSONField(default=list, verbose_name='所属组织')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('sidecar_result', models.JSONField(default=dict, verbose_name='sidecar结果')),
                ('executor_result', models.JSONField(default=dict, verbose_name='executor结果')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.controllertask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '控制器任务节点',
                'verbose_name_plural': '控制器任务节点',
                'db_table': 'controller_task_node',
            },
        ),
        migrations.CreateModel(
            name='CollectorTaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.node', verbose_name='节点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.collectortask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '采集器任务节点',
                'verbose_name_plural': '采集器任务节点',
                'db_table': 'collector_task_node',
            },
        ),
    ]
