# Generated by Django 4.2.7 on 2025-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0006_collectortask_controllertask_controllertasknode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('os', models.CharField(max_length=20, verbose_name='操作系统')),
                ('type', models.CharField(max_length=100, verbose_name='包类型(控制器/采集器)')),
                ('object', models.CharField(max_length=100, verbose_name='包对象')),
                ('version', models.CharField(max_length=100, verbose_name='包版本号')),
                ('name', models.CharField(max_length=100, verbose_name='包名称')),
                ('description', models.TextField(blank=True, verbose_name='包版本描述')),
            ],
            options={
                'verbose_name': '包版本信息',
                'verbose_name_plural': '包版本信息',
                'db_table': 'package_version',
            },
        ),
    ]
