# Generated by Django 4.2.7 on 2025-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0007_packageversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='object',
            field=models.CharField(db_index=True, max_length=100, verbose_name='包对象'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='os',
            field=models.CharField(db_index=True, max_length=20, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='type',
            field=models.CharField(db_index=True, max_length=100, verbose_name='包类型(控制器/采集器)'),
        ),
        migrations.AlterUniqueTogether(
            name='collector',
            unique_together={('node_operating_system', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together={('os', 'object', 'version')},
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], max_length=50, verbose_name='操作系统类型')),
                ('name', models.CharField(max_length=100, verbose_name='控制器名称')),
                ('description', models.TextField(blank=True, verbose_name='控制器描述')),
            ],
            options={
                'verbose_name': '控制器信息',
                'verbose_name_plural': '控制器信息',
                'db_table': 'controller',
                'unique_together': {('os', 'name')},
            },
        ),
    ]
