# Generated by Django 4.2.7 on 2025-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0008_alter_packageversion_object_alter_packageversion_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllertask',
            name='executor_package',
            field=models.IntegerField(default=0, verbose_name='executor版本'),
        ),
        migrations.AddField(
            model_name='controllertask',
            name='sidecar_package',
            field=models.IntegerField(default=0, verbose_name='sidecar版本'),
        ),
    ]
