# Generated by Django 4.2.7 on 2025-04-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0009_controllertask_executor_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageVersion',
        ),
        migrations.AddField(
            model_name='collectortask',
            name='collector_package',
            field=models.IntegerField(default=0, verbose_name='采集器版本ID'),
        ),
    ]
