# Generated by Django 4.2.7 on 2025-04-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0011_packageversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllertask',
            name='executor_package',
        ),
        migrations.RemoveField(
            model_name='controllertask',
            name='sidecar_package',
        ),
        migrations.RemoveField(
            model_name='controllertasknode',
            name='executor_result',
        ),
        migrations.RemoveField(
            model_name='controllertasknode',
            name='sidecar_result',
        ),
        migrations.AddField(
            model_name='controllertask',
            name='package_version',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.packageversion', verbose_name='控制器版本'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controllertasknode',
            name='result',
            field=models.JSONField(default=dict, verbose_name='结果'),
        ),
    ]
