# Generated by Django 4.2.7 on 2025-04-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0012_remove_controllertask_executor_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectortask',
            name='collector_package',
        ),
        migrations.RemoveField(
            model_name='collectortasknode',
            name='message',
        ),
        migrations.AddField(
            model_name='collectortask',
            name='package_version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.packageversion', verbose_name='采集器版本'),
        ),
        migrations.AddField(
            model_name='collectortasknode',
            name='result',
            field=models.JSONField(default=dict, verbose_name='结果'),
        ),
    ]
