# Generated by Django 4.2.7 on 2025-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0013_remove_collectortask_collector_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectortask',
            name='package_version',
        ),
        migrations.RemoveField(
            model_name='controllertask',
            name='package_version',
        ),
        migrations.AddField(
            model_name='collectortask',
            name='package_version_id',
            field=models.IntegerField(default=0, verbose_name='采集器版本'),
        ),
        migrations.AddField(
            model_name='controllertask',
            name='package_version_id',
            field=models.IntegerField(default=0, verbose_name='控制器版本'),
        ),
    ]
