# Generated by Django 4.2.7 on 2025-04-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0014_remove_collectortask_package_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectortasknode',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='collectortasknode',
            name='start_time',
        ),
    ]
