# Generated by Django 4.2.7 on 2025-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0015_remove_collectortasknode_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='icon',
            field=models.CharField(default='', max_length=100, verbose_name='图标key'),
        ),
    ]
