# Generated by Django 4.2.7 on 2025-02-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("channel_type", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("title", models.TextField()),
                ("app", models.CharField(max_length=100)),
                ("context", models.TextField()),
                (
                    "channel_obj",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="channel_mgmt.channel"),
                ),
            ],
        ),
    ]
