# Generated by Django 4.2.7 on 2024-10-14 03:02

import django_yaml_field.fields
from django.db import migrations, models

import apps.core.mixinx


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("enterprise_wechat", "Enterprise WeChat"),
                            ("enterprise_wechat_bot", "Enterprise WeChat Bot"),
                            ("ding_talk", "Ding Talk"),
                            ("web", "Web"),
                            ("gitlab", "GitLab"),
                        ],
                        max_length=100,
                        verbose_name="channel type",
                    ),
                ),
                (
                    "channel_config",
                    django_yaml_field.fields.YAMLField(blank=True, null=True, verbose_name="channel config"),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="enabled")),
            ],
            options={
                "verbose_name": "channel",
                "verbose_name_plural": "channel",
            },
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
    ]
