# Generated by Django 4.2.7 on 2025-03-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[("email", "Email"), ("enterprise_wechat", "Enterprise Wechat")], max_length=30
            ),
        ),
    ]
