# Generated by Django 4.2.7 on 2025-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel_mgmt", "0002_remove_channeltemplate_channel_obj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("enterprise_wechat", "Enterprise Wechat"),
                    ("enterprise_wechat_bot", "Enterprise Wechat Bot"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ChannelTemplate",
        ),
    ]
